# Sourced by all interactive shells.

export ZSH=$HOME/.oh-my-zsh
# For more options, check the oh-my-zsh zshrc template is at ~/.oh-my-zsh/templates/zshrc.zsh-template

# We use Starship but if removing, uncomment the line below and add a theme
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME=""

# The zsh-autosuggestions plugin can cause a very minor input lag. Async removes that.
ZSH_AUTOSUGGEST_USE_ASYNC=true

# Official Plugins: ~/.oh-my-zsh/plugins/*
# Custom Plugins: ~/.oh-my-zsh/custom/plugins/
plugins=(
  git
  docker
  docker-compose
  composer
  laravel
  npm
  mise
  zsh-autosuggestions
  zsh-completions
)
# Need to install first:
# git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
# ~/.fzf/install --all
# plugins+=(fzf)

# Note that zsh-syntax-highlighting must be the last plugin sourced.
plugins+=(zsh-syntax-highlighting)

# loads zsh-completions
autoload -U compinit && compinit

source $ZSH/oh-my-zsh.sh
# Official mise docs said to set this after sourcing oh-my-zsh
#plugins+=(mise)

###########################
## User configuration
##
## ENVIRONMENT VARIABLES:  .zshenv
## PATHS:                  .zshenv
## ALIASES:                ~/.oh-my-zsh/custom/aliases.zsh
## For a full list of active aliases, run `alias`.
##

# We use mise instead of NVM, but does this need to be here if using the plugin?
#eval "$(mise activate zsh)"

# Initialize Starship
eval "$(starship init zsh)"
