# Alacrity 0.15.1+ uses General for imports
[general]
import = [
  "~/.config/alacritty/themes/themes/nord.toml"
  #"~/.config/alacritty/themes/themes/pencil_light.toml"
  #"~/.config/alacritty/themes/themes/tomorrow_night.toml"
  #"~/.config/alacritty/themes/themes/one_dark.toml"
  #"~/.config/alacritty/themes/themes/catppuccin_latte.toml"
  #"~/.config/alacritty/themes/themes/oceanic_next.toml"
  #"~/.config/alacritty/themes/themes/dawnfox.toml"
]
#import = [ "~/.config/alacritty/theme.toml" ]

[env]
TERM = "xterm-256color"

[shell]
#program = "/usr/local/bin/zellij"
# We launch a real shell first (zsh here, but any shell works).
# That shell immediately starts Zellij.
# When Zellij exits or is detached, it falls back to ZSH instead of closing Alacritty.
# This allows attaching to different Zellij sessions without losing the Alacritty window.
program = "/bin/zsh"
args = ["-c", "zellij; exec zsh"]

[window]
# removes the top bar;
# Super + Left-click to drag window; Super + Middle click & drag to resize;
decorations = "None"
dimensions.columns = 121
dimensions.lines = 40
opacity = 0.98
# dynamic padding disabled for now as it causes issues with Ubuntu 25.04 + Tactile
# dynamic_padding = true

[window.padding]
x = 9
y = 9
# x = 16
# y = 14

[font]
# 100% = 14.0; 150% = 12.0; 200% = 9.0
size = 16.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
# normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
# bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
# italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }

